import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const usage = `Usage:
  node ./scripts/mock-data.mjs generate [--config ./mock-data.config.json] [--out ./tmp/mock-data.sql]

Notes:
  - Config must include real Supabase auth user IDs for each mock user.
  - Non-user entity IDs are generated deterministically from config keys.
`;

async function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === "--help" || command === "-h") {
    console.log(usage);
    process.exit(command ? 0 : 1);
  }

  if (command !== "generate") {
    throw new Error(`Unsupported command "${command}".`);
  }

  const options = parseOptions(args.slice(1));
  const configPath = path.resolve(process.cwd(), options.config ?? "./mock-data.config.json");
  const config = JSON.parse(await readFile(configPath, "utf8"));
  const sql = buildSql(config, configPath);

  if (options.out) {
    const outPath = path.resolve(process.cwd(), options.out);
    await mkdir(path.dirname(outPath), { recursive: true });
    await writeFile(outPath, sql);
    console.log(`Wrote ${path.relative(process.cwd(), outPath)}`);
    return;
  }

  process.stdout.write(sql);
}

function parseOptions(args) {
  const options = {};

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    const next = args[index + 1];

    if (arg === "--config") {
      if (!next) {
        throw new Error("Missing value for --config.");
      }

      options.config = next;
      index += 1;
      continue;
    }

    if (arg === "--out") {
      if (!next) {
        throw new Error("Missing value for --out.");
      }

      options.out = next;
      index += 1;
      continue;
    }

    throw new Error(`Unknown argument "${arg}".`);
  }

  return options;
}

function buildSql(config, configPath) {
  assertObject(config, "Mock data config must be a JSON object.");
  const users = assertArray(config.users, "config.users");
  const theaters = assertArray(config.theaters, "config.theaters");
  const shows = assertArray(config.shows, "config.shows");

  const userByKey = new Map();
  const theaterByKey = new Map();

  for (const user of users) {
    assertObject(user, "Each user must be an object.");
    const key = requireString(user.key, "users[].key");
    if (userByKey.has(key)) {
      throw new Error(`Duplicate user key "${key}".`);
    }

    userByKey.set(key, user);
  }

  for (const theater of theaters) {
    assertObject(theater, "Each theater must be an object.");
    const key = requireString(theater.key, "theaters[].key");
    if (theaterByKey.has(key)) {
      throw new Error(`Duplicate theater key "${key}".`);
    }

    theaterByKey.set(key, theater);
  }

  const lines = [];
  lines.push("-- Generated by project/scripts/mock-data.mjs");
  lines.push(`-- Source config: ${path.relative(process.cwd(), configPath)}`);
  lines.push("-- This file is deterministic for a given config.");
  lines.push("");

  pushCleanup(lines, users, theaters);
  pushTheaterUpserts(lines, theaters);
  pushProfileUpserts(lines, users, theaterByKey);
  pushMembershipUpserts(lines, theaters, userByKey);
  pushShowData(lines, shows, userByKey, theaterByKey);

  return `${lines.join("\n")}\n`;
}

function pushCleanup(lines, users, theaters) {
  const theaterIds = theaters.map((theater) => asSqlUuid(resolveTheaterId(theater)));
  const userIds = users.map((user) => asSqlUuid(requireUuid(user.id, `users[${user.key}].id`)));
  const mockUserKeys = users.map((user) => asSqlString(requireString(user.key, "users[].key")));

  if (theaterIds.length === 0 && userIds.length === 0 && mockUserKeys.length === 0) {
    return;
  }

  lines.push("-- Cleanup existing mock rows for this config");

  if (theaterIds.length > 0) {
    lines.push(`delete from theaters where id in (${theaterIds.join(", ")});`);
  }

  if (userIds.length > 0 || mockUserKeys.length > 0) {
    const conditions = [];

    if (userIds.length > 0) {
      conditions.push(`id in (${userIds.join(", ")})`);
    }

    if (mockUserKeys.length > 0) {
      conditions.push(`trust_flags->>'mock_user_key' in (${mockUserKeys.join(", ")})`);
    }

    lines.push(`delete from profiles where ${conditions.join(" or ")};`);
  }

  lines.push("");
}

function pushProfileUpserts(lines, users, theaterByKey) {
  if (users.length === 0) {
    return;
  }

  const rows = users.map((user) => {
    const userId = requireUuid(user.id, `users[${user.key}].id`);
    const homeTheaterId = user.homeTheater
      ? asSqlUuid(
          resolveTheaterId(
            requireTheater(
              theaterByKey,
              requireRef(user.homeTheater, user.key, "homeTheater"),
              user.key,
            ),
          ),
        )
      : "null";

    const trustFlags = {
      ...(user.trustFlags ?? {}),
      mock_user_key: user.key,
      mock_data: true,
    };

    return `  (${[
      asSqlUuid(userId),
      asSqlString(requireString(user.displayName, `users[${user.key}].displayName`)),
      asSqlNullableString(optionalString(user.avatarUrl)),
      asSqlString(optionalString(user.timezone) ?? "UTC"),
      asSqlNullableString(optionalString(user.pronouns)),
      asSqlNullableString(optionalString(user.bio)),
      asSqlNullableString(optionalString(user.city)),
      asSqlNullableString(optionalString(user.handle)),
      homeTheaterId,
      asSqlJson(user.contactLinks ?? {}),
      asSqlJson(user.notificationPreferences ?? {}),
      user.availability === undefined ? "null" : asSqlJson(user.availability),
      asSqlNullableString(optionalString(user.castingNotes)),
      asSqlEnum(optionalString(user.visibility) ?? "theater_only", "profile_visibility"),
      user.verifiedAt ? asSqlTimestamp(requireString(user.verifiedAt, `users[${user.key}].verifiedAt`)) : "null",
      asSqlJson(trustFlags),
      user.deletedAt ? asSqlTimestamp(requireString(user.deletedAt, `users[${user.key}].deletedAt`)) : "null",
    ].join(", ")})`;
  });

  lines.push("-- Profiles");
  lines.push(
    "insert into profiles (id, display_name, avatar_url, timezone, pronouns, bio, city, handle, home_theater_id, contact_links, notification_preferences, availability, casting_notes, visibility, verified_at, trust_flags, deleted_at)",
  );
  lines.push(`values\n${rows.join(",\n")}`);
  lines.push(
    "on conflict (id) do update set",
    "  display_name = excluded.display_name,",
    "  avatar_url = excluded.avatar_url,",
    "  timezone = excluded.timezone,",
    "  pronouns = excluded.pronouns,",
    "  bio = excluded.bio,",
    "  city = excluded.city,",
    "  handle = excluded.handle,",
    "  home_theater_id = excluded.home_theater_id,",
    "  contact_links = excluded.contact_links,",
    "  notification_preferences = excluded.notification_preferences,",
    "  availability = excluded.availability,",
    "  casting_notes = excluded.casting_notes,",
    "  visibility = excluded.visibility,",
    "  verified_at = excluded.verified_at,",
    "  trust_flags = excluded.trust_flags,",
    "  deleted_at = excluded.deleted_at;",
    "",
  );
}

function pushTheaterUpserts(lines, theaters) {
  if (theaters.length === 0) {
    return;
  }

  const rows = theaters.map((theater) => `  (${[
    asSqlUuid(resolveTheaterId(theater)),
    asSqlString(requireString(theater.name, `theaters[${theater.key}].name`)),
    asSqlString(requireString(theater.slug, `theaters[${theater.key}].slug`)),
    asSqlNullableString(optionalString(theater.tagline)),
    asSqlNullableString(optionalString(theater.street)),
    asSqlNullableString(optionalString(theater.city)),
    asSqlNullableString(optionalString(theater.stateRegion)),
    asSqlNullableString(optionalString(theater.postalCode)),
    asSqlNullableString(optionalString(theater.country)),
  ].join(", ")})`);

  lines.push("-- Theaters");
  lines.push(
    "insert into theaters (id, name, slug, tagline, street, city, state_region, postal_code, country)",
  );
  lines.push(`values\n${rows.join(",\n")}`);
  lines.push(
    "on conflict (id) do update set",
    "  name = excluded.name,",
    "  slug = excluded.slug,",
    "  tagline = excluded.tagline,",
    "  street = excluded.street,",
    "  city = excluded.city,",
    "  state_region = excluded.state_region,",
    "  postal_code = excluded.postal_code,",
    "  country = excluded.country;",
    "",
  );
}

function pushMembershipUpserts(lines, theaters, userByKey) {
  const rows = [];

  for (const theater of theaters) {
    const memberships = assertArray(theater.memberships ?? [], `theaters[${theater.key}].memberships`);
    const theaterId = resolveTheaterId(theater);

    for (const membership of memberships) {
      assertObject(membership, "Each membership must be an object.");
      const userKey = requireRef(membership.user, theater.key, "memberships[].user");
      const user = userByKey.get(userKey);
      if (!user) {
        throw new Error(`Unknown user key "${userKey}" in theater "${theater.key}".`);
      }

      const roles = assertArray(membership.roles, `theaters[${theater.key}].memberships[].roles`);
      if (roles.length === 0) {
        throw new Error(`Membership for user "${userKey}" in theater "${theater.key}" needs at least one role.`);
      }

      rows.push(`  (${[
        asSqlUuid(theaterId),
        asSqlUuid(user.id),
        asSqlEnumArray(roles, "theater_role"),
        asSqlEnum(optionalString(membership.status) ?? "active", "membership_status"),
      ].join(", ")})`);
    }
  }

  if (rows.length === 0) {
    return;
  }

  lines.push("-- Theater memberships");
  lines.push("insert into theater_memberships (theater_id, user_id, roles, status)");
  lines.push(`values\n${rows.join(",\n")}`);
  lines.push(
    "on conflict (theater_id, user_id) do update set",
    "  roles = excluded.roles,",
    "  status = excluded.status;",
    "",
  );
}

function pushShowData(lines, shows, userByKey, theaterByKey) {
  if (shows.length === 0) {
    return;
  }

  const showRows = [];
  const roleRows = [];
  const occurrenceRows = [];
  const castRows = [];
  const reviewRows = [];
  const notificationRows = [];
  const emailRows = [];

  for (const show of shows) {
    assertObject(show, "Each show must be an object.");
    const showKey = requireString(show.key, "shows[].key");
    const showId = entityId("show", showKey);
    const theaterKey = requireRef(show.theater, showKey, "theater");
    const theater = requireTheater(theaterByKey, theaterKey, showKey);

    const createdByKey = requireRef(show.createdBy, showKey, "createdBy");
    const createdBy = userByKey.get(createdByKey);
    if (!createdBy) {
      throw new Error(`Unknown user key "${createdByKey}" for show "${showKey}".`);
    }

    showRows.push(`  (${[
      asSqlUuid(showId),
      asSqlUuid(resolveTheaterId(theater)),
      asSqlUuid(createdBy.id),
      asSqlEnum(optionalString(show.status) ?? "draft", "show_status"),
      asSqlString(requireString(show.title, `shows[${showKey}].title`)),
      asSqlNullableString(optionalString(show.description)),
      asSqlEnum(optionalString(show.eventType) ?? "show", "event_type"),
      asSqlEnum(optionalString(show.castingMode) ?? "direct_invite", "casting_mode"),
      asSqlNullableInteger(optionalInteger(show.castMin)),
      asSqlNullableInteger(optionalInteger(show.castMax)),
      asSqlBoolean(Boolean(show.isCastFinalized)),
      asSqlBoolean(Boolean(show.isPublicListed)),
      asSqlNullableString(optionalString(show.ticketUrl)),
      show.onSaleAt ? asSqlTimestamp(requireString(show.onSaleAt, `shows[${showKey}].onSaleAt`)) : "null",
    ].join(", ")})`);

    const producers = assertArray(show.producers, `shows[${showKey}].producers`);
    if (producers.length === 0) {
      throw new Error(`Show "${showKey}" requires at least one producer.`);
    }

    for (const producerKey of producers) {
      const producer = userByKey.get(requireRef(producerKey, showKey, "producers[]"));
      if (!producer) {
        throw new Error(`Unknown producer key "${producerKey}" for show "${showKey}".`);
      }

      roleRows.push(`  (${[
        asSqlUuid(showId),
        asSqlUuid(producer.id),
        asSqlEnum("producer", "show_role"),
      ].join(", ")})`);
    }

    for (const occurrence of assertArray(show.occurrences ?? [], `shows[${showKey}].occurrences`)) {
      assertObject(occurrence, "Each occurrence must be an object.");
      const occurrenceKey = requireString(occurrence.key, `shows[${showKey}].occurrences[].key`);
      occurrenceRows.push(`  (${[
        asSqlUuid(entityId("occurrence", `${showKey}:${occurrenceKey}`)),
        asSqlUuid(showId),
        asSqlTimestamp(requireString(occurrence.startsAt, `shows[${showKey}].occurrences[].startsAt`)),
        occurrence.endsAt
          ? asSqlTimestamp(requireString(occurrence.endsAt, `shows[${showKey}].occurrences[].endsAt`))
          : "null",
        asSqlEnum(optionalString(occurrence.status) ?? "scheduled", "show_occurrence_status"),
      ].join(", ")})`);
    }

    for (const cast of assertArray(show.cast ?? [], `shows[${showKey}].cast`)) {
      assertObject(cast, "Each cast entry must be an object.");
      const castUserKey = requireRef(cast.user, showKey, "cast[].user");
      const castUser = userByKey.get(castUserKey);
      if (!castUser) {
        throw new Error(`Unknown cast user key "${castUserKey}" for show "${showKey}".`);
      }

      castRows.push(`  (${[
        asSqlUuid(showId),
        asSqlUuid(castUser.id),
        asSqlEnum(optionalString(cast.source) ?? "invited", "show_cast_source"),
        asSqlEnum(optionalString(cast.status) ?? "pending", "show_cast_status"),
        asSqlNullableInteger(optionalInteger(cast.programOrder)),
        asSqlNullableString(optionalString(cast.note)),
      ].join(", ")})`);
    }

    for (const review of assertArray(show.reviewEvents ?? [], `shows[${showKey}].reviewEvents`)) {
      assertObject(review, "Each review event must be an object.");
      const actorKey = requireRef(review.actor, showKey, "reviewEvents[].actor");
      const actor = userByKey.get(actorKey);
      if (!actor) {
        throw new Error(`Unknown review event actor key "${actorKey}" for show "${showKey}".`);
      }

      const reviewKey = requireString(review.key, `shows[${showKey}].reviewEvents[].key`);
      reviewRows.push(`  (${[
        asSqlUuid(entityId("review", `${showKey}:${reviewKey}`)),
        asSqlUuid(showId),
        asSqlEnum(optionalString(review.action) ?? "submitted", "review_action"),
        asSqlUuid(actor.id),
        asSqlNullableString(optionalString(review.note)),
      ].join(", ")})`);
    }

    for (const notification of assertArray(show.notifications ?? [], `shows[${showKey}].notifications`)) {
      assertObject(notification, "Each notification must be an object.");
      const recipientKey = requireRef(notification.user, showKey, "notifications[].user");
      const recipient = userByKey.get(recipientKey);
      if (!recipient) {
        throw new Error(`Unknown notification user key "${recipientKey}" for show "${showKey}".`);
      }

      notificationRows.push(`  (${[
        asSqlUuid(entityId("notification", `${showKey}:${requireString(notification.key, `shows[${showKey}].notifications[].key`)}`)),
        asSqlUuid(recipient.id),
        asSqlString(requireString(notification.type, `shows[${showKey}].notifications[].type`)),
        asSqlEnum(optionalString(notification.entityType) ?? "show", "notification_entity"),
        asSqlUuid(resolveEntityId(notification.entity ?? { type: "show", key: showKey }, showKey)),
        asSqlJson(notification.payload ?? {}),
        asSqlString(requireString(notification.dedupeKey, `shows[${showKey}].notifications[].dedupeKey`)),
        notification.readAt
          ? asSqlTimestamp(requireString(notification.readAt, `shows[${showKey}].notifications[].readAt`))
          : "null",
      ].join(", ")})`);
    }

    for (const email of assertArray(show.emailOutbox ?? [], `shows[${showKey}].emailOutbox`)) {
      assertObject(email, "Each email outbox entry must be an object.");
      const userKey = requireRef(email.user, showKey, "emailOutbox[].user");
      const user = userByKey.get(userKey);
      if (!user) {
        throw new Error(`Unknown email outbox user key "${userKey}" for show "${showKey}".`);
      }

      emailRows.push(`  (${[
        asSqlUuid(entityId("email", `${showKey}:${requireString(email.key, `shows[${showKey}].emailOutbox[].key`)}`)),
        asSqlUuid(user.id),
        asSqlString(requireString(email.template, `shows[${showKey}].emailOutbox[].template`)),
        asSqlJson(email.payload ?? {}),
        asSqlString(requireString(email.dedupeKey, `shows[${showKey}].emailOutbox[].dedupeKey`)),
        asSqlEnum(optionalString(email.status) ?? "queued", "email_outbox_status"),
        email.sentAt
          ? asSqlTimestamp(requireString(email.sentAt, `shows[${showKey}].emailOutbox[].sentAt`))
          : "null",
        asSqlNullableString(optionalString(email.lastError)),
      ].join(", ")})`);
    }
  }

  pushInsert(lines, "-- Shows", "shows", "(id, theater_id, created_by_user_id, status, title, description, event_type, casting_mode, cast_min, cast_max, is_cast_finalized, is_public_listed, ticket_url, on_sale_at)", showRows, [
    "on conflict (id) do update set",
    "  theater_id = excluded.theater_id,",
    "  created_by_user_id = excluded.created_by_user_id,",
    "  status = excluded.status,",
    "  title = excluded.title,",
    "  description = excluded.description,",
    "  event_type = excluded.event_type,",
    "  casting_mode = excluded.casting_mode,",
    "  cast_min = excluded.cast_min,",
    "  cast_max = excluded.cast_max,",
    "  is_cast_finalized = excluded.is_cast_finalized,",
    "  is_public_listed = excluded.is_public_listed,",
    "  ticket_url = excluded.ticket_url,",
    "  on_sale_at = excluded.on_sale_at;",
  ]);
  pushInsert(lines, "-- Show roles", "show_roles", "(show_id, user_id, role)", roleRows, [
    "on conflict (show_id, user_id, role) do nothing;",
  ]);
  pushInsert(lines, "-- Show occurrences", "show_occurrences", "(id, show_id, starts_at, ends_at, status)", occurrenceRows, [
    "on conflict (id) do update set",
    "  show_id = excluded.show_id,",
    "  starts_at = excluded.starts_at,",
    "  ends_at = excluded.ends_at,",
    "  status = excluded.status;",
  ]);
  pushInsert(lines, "-- Show cast", "show_cast", "(show_id, user_id, source, status, program_order, note)", castRows, [
    "on conflict (show_id, user_id) do update set",
    "  source = excluded.source,",
    "  status = excluded.status,",
    "  program_order = excluded.program_order,",
    "  note = excluded.note;",
  ]);
  pushInsert(lines, "-- Show review events", "show_review_events", "(id, show_id, action, actor_user_id, note)", reviewRows, [
    "on conflict (id) do update set",
    "  show_id = excluded.show_id,",
    "  action = excluded.action,",
    "  actor_user_id = excluded.actor_user_id,",
    "  note = excluded.note;",
  ]);
  pushInsert(lines, "-- Notifications", "notifications", "(id, user_id, type, entity_type, entity_id, payload, dedupe_key, read_at)", notificationRows, [
    "on conflict (user_id, dedupe_key) do update set",
    "  type = excluded.type,",
    "  entity_type = excluded.entity_type,",
    "  entity_id = excluded.entity_id,",
    "  payload = excluded.payload,",
    "  read_at = excluded.read_at;",
  ]);
  pushInsert(lines, "-- Email outbox", "email_outbox", "(id, user_id, template, payload, dedupe_key, status, sent_at, last_error)", emailRows, [
    "on conflict (id) do update set",
    "  user_id = excluded.user_id,",
    "  template = excluded.template,",
    "  payload = excluded.payload,",
    "  dedupe_key = excluded.dedupe_key,",
    "  status = excluded.status,",
    "  sent_at = excluded.sent_at,",
    "  last_error = excluded.last_error;",
  ]);
}

function pushInsert(lines, comment, table, columns, rows, footer) {
  if (rows.length === 0) {
    return;
  }

  lines.push(comment);
  lines.push(`insert into ${table} ${columns}`);
  lines.push(`values\n${rows.join(",\n")}`);
  lines.push(...footer);
  lines.push("");
}

function resolveEntityId(entity, showKey) {
  assertObject(entity, `Entity reference for show "${showKey}" must be an object.`);
  const type = requireString(entity.type, `entity.type for show "${showKey}"`);
  const key = requireString(entity.key, `entity.key for show "${showKey}"`);

  if (type === "show") {
    return entityId("show", key);
  }

  if (type === "occurrence") {
    return entityId("occurrence", `${showKey}:${key}`);
  }

  if (type === "cast") {
    return entityId("show", showKey);
  }

  throw new Error(`Unsupported notification entity type "${type}" in show "${showKey}".`);
}

function requireTheater(theaterByKey, theaterKey, ownerKey) {
  const theater = theaterByKey.get(theaterKey);
  if (!theater) {
    throw new Error(`Unknown theater key "${theaterKey}" in "${ownerKey}".`);
  }

  return theater;
}

function resolveTheaterId(theater) {
  const explicitId = optionalString(theater.id);
  if (explicitId) {
    return requireUuid(explicitId, `theaters[${theater.key}].id`);
  }

  return entityId("theater", theater.key);
}

function entityId(scope, key, registry) {
  if (registry && !registry.has(key)) {
    throw new Error(`Unknown ${scope} key "${key}".`);
  }

  return deterministicUuid(`stagecom:${scope}:${key}`);
}

function deterministicUuid(input) {
  const hex = createHash("sha1").update(input).digest("hex").slice(0, 32).split("");
  hex[12] = "5";
  hex[16] = "8";

  return [
    hex.slice(0, 8).join(""),
    hex.slice(8, 12).join(""),
    hex.slice(12, 16).join(""),
    hex.slice(16, 20).join(""),
    hex.slice(20, 32).join(""),
  ].join("-");
}

function assertObject(value, message) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(message);
  }

  return value;
}

function assertArray(value, pathLabel) {
  if (!Array.isArray(value)) {
    throw new Error(`${pathLabel} must be an array.`);
  }

  return value;
}

function requireString(value, pathLabel) {
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`${pathLabel} must be a non-empty string.`);
  }

  return value.trim();
}

function optionalString(value) {
  if (value === undefined || value === null || value === "") {
    return null;
  }

  if (typeof value !== "string") {
    throw new Error("Expected an optional string value.");
  }

  return value;
}

function optionalInteger(value) {
  if (value === undefined || value === null || value === "") {
    return null;
  }

  if (!Number.isInteger(value)) {
    throw new Error(`Expected integer value, received "${value}".`);
  }

  return value;
}

function requireUuid(value, pathLabel) {
  const stringValue = requireString(value, pathLabel);
  const uuidPattern =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

  if (!uuidPattern.test(stringValue)) {
    throw new Error(`${pathLabel} must be a UUID.`);
  }

  return stringValue;
}

function requireRef(value, ownerKey, pathLabel) {
  return requireString(value, `${pathLabel} in "${ownerKey}"`);
}

function asSqlString(value) {
  return `'${value.replaceAll("'", "''")}'`;
}

function asSqlNullableString(value) {
  return value === null ? "null" : asSqlString(value);
}

function asSqlUuid(value) {
  return `${asSqlString(value)}::uuid`;
}

function asSqlJson(value) {
  return `${asSqlString(JSON.stringify(value))}::jsonb`;
}

function asSqlEnum(value, enumName) {
  return `${asSqlString(value)}::${enumName}`;
}

function asSqlEnumArray(values, enumName) {
  return `array[${values.map((value) => asSqlEnum(requireString(value, `${enumName}[]`), enumName)).join(", ")}]`;
}

function asSqlTimestamp(value) {
  return `${asSqlString(value)}::timestamptz`;
}

function asSqlBoolean(value) {
  return value ? "true" : "false";
}

function asSqlNullableInteger(value) {
  return value === null ? "null" : String(value);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
