export const DEFAULT_THEATER_UPCOMING_SHOWS_LIMIT = 5;
export const DEFAULT_THEATER_UPCOMING_OTHER_EVENTS_LIMIT = 5;

export const MIN_THEATER_UPCOMING_ITEMS_LIMIT = 1;
export const MAX_THEATER_UPCOMING_ITEMS_LIMIT = 12;
